env:
  global:
    - CC_TEST_REPORTER_ID=95195708d4def2c550a4df8717aea0780b0afa0d61e4f54ec2aa48f124c9acf1

language: java
jdk:
  - openjdk11

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter format-coverage -d -t jacoco /home/travis/build/Mikhail57/python-interpreter/build/reports/jacoco/test/jacocoTestReport.xml
  - ./cc-test-reporter upload-coverage -d